### ISSUE TITLE
Error when using Dict[str, Any] as type in dataclass

### ISSUE THREAD

**Issue by snorfalorpagus** [s-knibbs/dataclasses-jsonschema#2]
I'm getting an error when trying to use `Dict[str, Any]` as a type in a dataclass, see example below.

```python
from dataclasses import dataclass
from dataclasses_jsonschema import JsonSchemaMixin
from typing import Dict, Any


@dataclass
class Feature(JsonSchemaMixin):
    id: int
    properties: Dict[str, Any]
    geometry: Dict[str, Any]


feature = Feature(
    id=1,
    properties={"a": 1, "b": "xyz"},
    geometry={"type": "Point", "coordinates": [1.2, 3.4]}
)

# round-trip
assert feature.to_dict() == Feature.from_dict(feature.to_dict()).to_dict()
```

The exception is:
```python traceback
/home/snorf/.local/share/virtualenvs/my-project-cQlQitVM/lib/python3.6/site-packages/dataclasses_jsonschema.py:219: UserWarning: Unable to create schema for 'None'
  warnings.warn(f"Unable to create schema for '{field_type_name}'")
Traceback (most recent call last):
  File "bug.py", line 20, in <module>
    assert feature.to_dict() == Feature.from_dict(feature.to_dict()).to_dict()
  File "/home/snorf/.local/share/virtualenvs/my-project-cQlQitVM/lib/python3.6/site-packages/dataclasses_jsonschema.py", line 171, in from_dict
    schema_validate(data, cls.json_schema())
  File "/home/snorf/.local/share/virtualenvs/my-project-cQlQitVM/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/snorf/.local/share/virtualenvs/my-project-cQlQitVM/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'xyz' is not of type 'object'

Failed validating 'type' in schema['properties']['properties']['additionalProperties']:
    {'type': 'object'}

On instance['properties']['b']:
    'xyz'
```

Tested on Python 3.6 on Linux.

**Comment by snorfalorpagus** [comment]
Perhaps this is related to lack of support for Union?
