### ISSUE TITLE
Cannot install with pipenv SSLCertVerificationError

### ISSUE THREAD

**Issue by Mulugruntz** [s-knibbs/dataclasses-jsonschema#5]
Hi,

I have managed to install `dataclasses-jsonschema` on a local machine, but it seems to be impossible to install on a remote machine (GCE instance).
They are both Windows 10, same Python 3.7 build, same pipenv build, same pip build.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'C:\\Python37\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Python37\\python.exe'`

Python installations found:

  - `3.7.0`: `C:\Python37\python.exe`
  - `2.7`: `C:\Python27\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.14393',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CHOCOLATEYTOOLSLOCATION`
  - `CLIENTNAME`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `GOOGETROOT`
  - `GROOVY_HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `WIXSHARP_DIR`
  - `WIXSHARP_WIXDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\Python37\Scripts\;C:\Python37\;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\tools\groovy-2.4.13\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Perforce;C:\Program Files\Perforce\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps`

---------------------------

Contents of `Pipfile` ('C:\\jenkins\\workspace\\mpto-assets-migrator_master-W24OXHX6O6XT4BHM3AUCEGUVPKCE3IDTNCLQDKID4BJYVHOO6L6A\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
aiohttp = "==3.4.4"
click = "==6.7"
aiostream = "==0.3.1"
aiofiles = "==0.4.0"
black = "==18.9b0"
dataclasses-jsonschema = "==1.3.0"
asyncwrap = "==0.1.0"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('C:\\jenkins\\workspace\\mpto-assets-migrator_master-W24OXHX6O6XT4BHM3AUCEGUVPKCE3IDTNCLQDKID4BJYVHOO6L6A\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "affdff9fcf0faffc5e0db889cb25f6c677c6c46040ab6045aafbed864920befc"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "aiofiles": {
            "hashes": [
                "sha256:021ea0ba314a86027c166ecc4b4c07f2d40fc0f4b3a950d1868a0f2571c2bbee",
                "sha256:1e644c2573f953664368de28d2aa4c89dfd64550429d0c27c4680ccd3aa4985d"
            ],
            "index": "pypi",
            "version": "==0.4.0"
        },
        "aiohttp": {
            "hashes": [
                "sha256:0419705a36b43c0ac6f15469f9c2a08cad5c939d78bd12a5c23ea167c8253b2b",
                "sha256:1812fc4bc6ac1bde007daa05d2d0f61199324e0cc893b11523e646595047ca08",
                "sha256:2214b5c0153f45256d5d52d1e0cafe53f9905ed035a142191727a5fb620c03dd",
                "sha256:275909137f0c92c61ba6bb1af856a522d5546f1de8ea01e4e726321c697754ac",
                "sha256:3983611922b561868428ea1e7269e757803713f55b53502423decc509fef1650",
                "sha256:51afec6ffa50a9da4cdef188971a802beb1ca8e8edb40fa429e5e529db3475fa",
                "sha256:589f2ec8a101a0f340453ee6945bdfea8e1cd84c8d88e5be08716c34c0799d95",
                "sha256:789820ddc65e1f5e71516adaca2e9022498fa5a837c79ba9c692a9f8f916c330",
                "sha256:7a968a0bdaaf9abacc260911775611c9a602214a23aeb846f2eb2eeaa350c4dc",
                "sha256:7aeefbed253f59ea39e70c5848de42ed85cb941165357fc7e87ab5d8f1f9592b",
                "sha256:7b2eb55c66512405103485bd7d285a839d53e7fdc261ab20e5bcc51d7aaff5de",
                "sha256:87bc95d3d333bb689c8d755b4a9d7095a2356108002149523dfc8e607d5d32a4",
                "sha256:9d80e40db208e29168d3723d1440ecbb06054d349c5ece6a2c5a611490830dd7",
                "sha256:a1b442195c2a77d33e4dbee67c9877ccbdd3a1f686f91eb479a9577ed8cc326b",
                "sha256:ab3d769413b322d6092f169f316f7b21cd261a7589f7e31db779d5731b0480d8",
                "sha256:b066d3dec5d0f5aee6e34e5765095dc3d6d78ef9839640141a2b20816a0642bd",
                "sha256:b24e7845ae8de3e388ef4bcfcf7f96b05f52c8e633b33cf8003a6b1d726fc7c2",
                "sha256:c59a953c3f8524a7c86eaeaef5bf702555be12f5668f6384149fe4bb75c52698",
                "sha256:cf2cc6c2c10d242790412bea7ccf73726a9a44b4c4b073d2699ef3b48971fd95",
                "sha256:e0c9c8d4150ae904f308ff27b35446990d2b1dfc944702a21925937e937394c6",
                "sha256:f1839db4c2b08a9c8f9788112644f8a8557e8e0ecc77b07091afabb941dc55d0",
                "sha256:f3df52362be39908f9c028a65490fae0475e4898b43a03d8aa29d1e765b45e07"
            ],
            "index": "pypi",
            "version": "==3.4.4"
        },
        "aiostream": {
            "hashes": [
                "sha256:2f7be31c02789975269d91c5fa5764661fae9562682e29630b964f5f83383e2e"
            ],
            "index": "pypi",
            "version": "==0.3.1"
        },
        "appdirs": {
            "hashes": [
                "sha256:9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92",
                "sha256:d8b24664561d0d34ddfaec54636d502d7cea6e29c3eaf68f3df6180863e2166e"
            ],
            "version": "==1.4.3"
        },
        "async-timeout": {
            "hashes": [
                "sha256:0c3c816a028d47f659d6ff5c745cb2acf1f966da1fe5c19c77a70282b25f4c5f",
                "sha256:4291ca197d287d274d0b6cb5d6f8f8f82d434ed288f962539ff18cc9012f9ea3"
            ],
            "markers": "python_version >= '3.5.3'",
            "version": "==3.0.1"
        },
        "asyncwrap": {
            "hashes": [
                "sha256:f0e06f02cc20807309687a989cb47fbe824482cbd4b657bc9f510596f9ccaf9a"
            ],
            "index": "pypi",
            "version": "==0.1.0"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "black": {
            "hashes": [
                "sha256:817243426042db1d36617910df579a54f1afd659adb96fc5032fcf4b36209739",
                "sha256:e030a9a28f542debc08acceb273f228ac422798e5215ba2a791a6ddeaaca22a5"
            ],
            "index": "pypi",
            "version": "==18.9b0"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "index": "pypi",
            "version": "==6.7"
        },
        "dataclasses-jsonschema": {
            "hashes": [
                "sha256:b95008ff766221f310949057a1719b1962bd67da774b43902cbad14f7b92e7ce"
            ],
            "index": "pypi",
            "version": "==1.3.0"
        },
        "idna": {
            "hashes": [
                "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
                "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"
            ],
            "version": "==2.7"
        },
        "jsonschema": {
            "hashes": [
                "sha256:000e68abd33c972a5248544925a0cae7d1125f9bf6c58280d37546b946769a08",
                "sha256:6ff5f3180870836cae40f06fa10419f557208175f13ad7bc26caa77beb1f6e02"
            ],
            "version": "==2.6.0"
        },
        "multidict": {
            "hashes": [
                "sha256:05eeab69bf2b0664644c62bd92fabb045163e5b8d4376a31dfb52ce0210ced7b",
                "sha256:0c85880efa7cadb18e3b5eef0aa075dc9c0a3064cbbaef2e20be264b9cf47a64",
                "sha256:136f5a4a6a4adeacc4dc820b8b22f0a378fb74f326e259c54d1817639d1d40a0",
                "sha256:14906ad3347c7d03e9101749b16611cf2028547716d0840838d3c5e2b3b0f2d3",
                "sha256:1ade4a3b71b1bf9e90c5f3d034a87fe4949c087ef1f6cd727fdd766fe8bbd121",
                "sha256:22939a00a511a59f9ecc0158b8db728afef57975ce3782b3a265a319d05b9b12",
                "sha256:2b86b02d872bc5ba5b3a4530f6a7ba0b541458ab4f7c1429a12ac326231203f7",
                "sha256:3c11e92c3dfc321014e22fb442bc9eb70e01af30d6ce442026b0c35723448c66",
                "sha256:4ba3bd26f282b201fdbce351f1c5d17ceb224cbedb73d6e96e6ce391b354aacc",
                "sha256:4c6e78d042e93751f60672989efbd6a6bc54213ed7ff695fff82784bbb9ea035",
                "sha256:4d80d1901b89cc935a6cf5b9fd89df66565272722fe2e5473168927a9937e0ca",
                "sha256:4fcf71d33178a00cc34a57b29f5dab1734b9ce0f1c97fb34666deefac6f92037",
                "sha256:52f7670b41d4b4d97866ebc38121de8bcb9813128b7c4942b07794d08193c0ab",
                "sha256:5368e2b7649a26b7253c6c9e53241248aab9da49099442f5be238fde436f18c9",
                "sha256:5bb65fbb48999044938f0c0508e929b14a9b8bf4939d8263e9ea6691f7b54663",
                "sha256:60672bb5577472800fcca1ac9dae232d1461db9f20f055184be8ce54b0052572",
                "sha256:669e9be6d148fc0283f53e17dd140cde4dc7c87edac8319147edd5aa2a830771",
                "sha256:6a0b7a804e8d1716aa2c72e73210b48be83d25ba9ec5cf52cf91122285707bb1",
                "sha256:79034ea3da3cf2a815e3e52afdc1f6c1894468c98bdce5d2546fa2342585497f",
                "sha256:79247feeef6abcc11137ad17922e865052f23447152059402fc320f99ff544bb",
                "sha256:81671c2049e6bf42c7fd11a060f8bc58f58b7b3d6f3f951fc0b15e376a6a5a98",
                "sha256:82ac4a5cb56cc9280d4ae52c2d2ebcd6e0668dd0f9ef17f0a9d7c82bd61e24fa",
                "sha256:9436267dbbaa49dad18fbbb54f85386b0f5818d055e7b8e01d219661b6745279",
                "sha256:94e4140bb1343115a1afd6d84ebf8fca5fb7bfb50e1c2cbd6f2fb5d3117ef102",
                "sha256:a2cab366eae8a0ffe0813fd8e335cf0d6b9bb6c5227315f53bb457519b811537",
                "sha256:a596019c3eafb1b0ae07db9f55a08578b43c79adb1fe1ab1fd818430ae59ee6f",
                "sha256:e8848ae3cd6a784c29fae5055028bee9bffcc704d8bcad09bd46b42b44a833e2",
                "sha256:e8a048bfd7d5a280f27527d11449a509ddedf08b58a09a24314828631c099306",
                "sha256:f6dd28a0ac60e2426a6918f36f1b4e2620fc785a0de7654cd206ba842eee57fd"
            ],
            "markers": "python_version >= '3.4.1'",
            "version": "==4.4.2"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:1adb80e7a782c12e52ef9a8182bebeb73f1d7e24e374397af06fb4956c8dc5c0",
                "sha256:e27001de32f627c22380a688bcc43ce83504a7bc5da472209b4c70f02829f0b8"
            ],
            "version": "==2.7.3"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "toml": {
            "hashes": [
                "sha256:229f81c57791a41d65e399fc06bf0848bab550a9dfd5ed66df18ce5f05e73d5c",
                "sha256:235682dd292d5899d361a811df37e04a8828a5b1da3115886b73cf81ebc9100e"
            ],
            "version": "==0.10.0"
        },
        "yarl": {
            "hashes": [
                "sha256:2556b779125621b311844a072e0ed367e8409a18fa12cbd68eb1258d187820f9",
                "sha256:4aec0769f1799a9d4496827292c02a7b1f75c0bab56ab2b60dd94ebb57cbd5ee",
                "sha256:55369d95afaacf2fa6b49c84d18b51f1704a6560c432a0f9a1aeb23f7b971308",
                "sha256:6c098b85442c8fe3303e708bbb775afd0f6b29f77612e8892627bcab4b939357",
                "sha256:9182cd6f93412d32e009020a44d6d170d2093646464a88aeec2aef50592f8c78",
                "sha256:c8cbc21bbfa1dd7d5386d48cc814fe3d35b80f60299cdde9279046f399c3b0d8",
                "sha256:db6f70a4b09cde813a4807843abaaa60f3b15fb4a2a06f9ae9c311472662daa1",
                "sha256:f17495e6fe3d377e3faac68121caef6f974fcb9e046bc075bcff40d8e5cc69a4",
                "sha256:f85900b9cca0c67767bb61b2b9bd53208aaa7373dae633dbe25d179b4bf38aa7"
            ],
            "version": "==1.2.6"
        }
    },
    "develop": {}
}

```
</details>

When I do `python -m pipenv install dataclasses-jsonschema==1.3.0` the same thing happens as when I do `python -m pipenv install`:

```
An error occurred while installing dataclasses-jsonschema==1.3.0 --hash=sha256:b95008ff766221f310949057a1719b1962bd67da774b43902cbad14f7b92e7ce! Will try again.
Installing initially failed dependencies…
Collecting dataclasses-jsonschema==1.3.0 
  Using cached https://files.pythonhosted.org/packages/81/70/6a2ea82f8c7bb297bab4a172febdb3b161b907b2cab521d919401652cf5e/dataclasses-jsonschema-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Python37\Lib\urllib\request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "C:\Python37\Lib\http\client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Python37\Lib\http\client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Python37\Lib\http\client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Python37\Lib\http\client.py", line 1016, in _send_output
        self.send(msg)
      File "C:\Python37\Lib\http\client.py", line 956, in send
        self.connect()
      File "C:\Python37\Lib\http\client.py", line 1392, in connect
        server_hostname=server_hostname)
      File "C:\Python37\Lib\ssl.py", line 412, in wrap_socket
        session=session
      File "C:\Python37\Lib\ssl.py", line 850, in _create
        self.do_handshake()
      File "C:\Python37\Lib\ssl.py", line 1108, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 765, in open_url
        return open_with_auth(url, self.opener)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 959, in _socket_timeout
        return func(*args, **kwargs)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 1078, in open_with_auth
        fp = opener(request)
      File "C:\Python37\Lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Python37\Lib\urllib\request.py", line 525, in open
        response = self._open(req, data)
      File "C:\Python37\Lib\urllib\request.py", line 543, in _open
        '_open', req)
      File "C:\Python37\Lib\urllib\request.py", line 503, in _call_chain
        result = func(*args)
      File "C:\Python37\Lib\urllib\request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Python37\Lib\urllib\request.py", line 1319, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-7r15ad19\dataclasses-jsonschema\setup.py", line 37, in <module>
        'Topic :: Software Development :: Libraries'
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\__init__.py", line 139, in setup
        _install_setup_requires(attrs)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\__init__.py", line 134, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\pkg_resources\__init__.py", line 1060, in best_match
        return self.obtain(req, installer)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\pkg_resources\__init__.py", line 1072, in obtain
        return installer(requirement)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\command\easy_install.py", line 664, in easy_install
        not self.always_copy, self.local_index
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 654, in fetch_distribution
        dist = find(requirement)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 634, in find
        loc = self.download(dist.location, tmpdir)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 578, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 823, in _download_url
        return self._attempt_download(url, filename)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 829, in _attempt_download
        headers = self._download_to(url, filename)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 728, in _download_to
        fp = self.open_url(url)
      File "c:\users\admin\.virtualenvs\mpto-assets-migrator_master-w24oxhx6o6xt4b-g2dsurfx\lib\site-packages\setuptools\package_index.py", line 779, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/b2/d5/970632917c53a1fb2751f7da8b288d26546f2b113e4321674051fc9f81e4/setuptools_scm-3.1.0-py2.py3-none-any.whl#sha256=cc6953d224a22f10e933fa2f55c95979317c55259016adcf93310ba2997febfa: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-7r15ad19\dataclasses-jsonschema\
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Regards

**Comment by Mulugruntz** [comment]
The result is the same with pip.

I used `C:\Python37\python.exe -m pipenv run python -m pip install dataclasses-jsonschema==1.3.0` to make sure that I used the right environment.

**Comment by Mulugruntz** [comment]
Nevermind about the `MANIFEST.in` part. It's just that I was not in the directorty where the setup.py is. And that setuptools cannot work otherwise -_-.

**Comment by Mulugruntz** [comment]
I've found something.

If I do `C:\Python37\python.exe -m pipenv run python -m pip install setuptools-scm pytest-runner`
then `C:\Python37\python.exe -m pipenv install`, it seems to work.

So the problem would be this line https://github.com/Mulugruntz/dataclasses-jsonschema/blob/shipping-readme-in-egg/setup.py#L26 `setup_requires=['pytest-runner', 'setuptools_scm'],`

**Comment by snorfalorpagus** [comment]
I have no problems installing this with pipenv locally:

```
➜  test pipenv install dataclasses-jsonschema==1.3.0
Installing dataclasses-jsonschema==1.3.0…
Collecting dataclasses-jsonschema==1.3.0
Collecting dataclasses; python_version < "3.7" (from dataclasses-jsonschema==1.3.0)
  Using cached https://files.pythonhosted.org/packages/26/2f/1095cdc2868052dd1e64520f7c0d5c8c550ad297e944e641dbf1ffbb9a5d/dataclasses-0.6-py3-none-any.whl
Collecting jsonschema (from dataclasses-jsonschema==1.3.0)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting python-dateutil (from dataclasses-jsonschema==1.3.0)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Requirement not upgraded as not directly required: six>=1.5 in /home/snorf/.local/share/virtualenvs/tmp-t306Fniu/lib/python3.6/site-packages (from python-dateutil->dataclasses-jsonschema==1.3.0) (1.11.0)
Installing collected packages: dataclasses, jsonschema, python-dateutil, dataclasses-jsonschema
Successfully installed dataclasses-0.6 dataclasses-jsonschema-1.3.0 jsonschema-2.6.0 python-dateutil-2.8.0

Adding dataclasses-jsonschema to Pipfile's [packages]…
Pipfile.lock (7ce025) out of date, updating to (ca7157)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (7ce025)!
Installing dependencies from Pipfile.lock (7ce025)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
➜  test pipenv shell
Launching subshell in virtual environment…
 . /home/snorf/.local/share/virtualenvs/tmp-t306Fniu/bin/activate
➜  tmp  . /home/snorf/.local/share/virtualenvs/tmp-t306Fniu/bin/activate
(tmp-t306Fniu) ➜  tmp python
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataclasses_jsonschema
>>>
```

**Comment by s-knibbs** [comment]
Closing this as it looks like a local installation issue. You might be missing a root certificate required for SSL validation.
