### ISSUE TITLE
DataclassesPlugin: DuplicateComponentNameError

### ISSUE THREAD

**Issue by ZdenekM** [s-knibbs/dataclasses-jsonschema#90]
Hello. I'm not 100% sure if this is issue with DataclassesPlugin or apispec, or whatever else :) Here is an example I would expect to work, but it raises ```DuplicateComponentNameError```:

```py
from typing import Optional, List
from dataclasses import dataclass

from apispec import APISpec

from dataclasses_jsonschema.apispec import DataclassesPlugin
from dataclasses_jsonschema import JsonSchemaMixin


# Create an APISpec
spec = APISpec(
    title="Swagger Petstore",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[DataclassesPlugin()],
)


@dataclass
class Category(JsonSchemaMixin):
    """Pet category"""
    name: str
    id: Optional[int]

@dataclass
class Pet(JsonSchemaMixin):
    """A pet"""
    categories: List[Category]
    name: str
    
@dataclass
class Cat(Pet):
    """A cat"""
    color: str

# Dependant schemas (e.g. 'Category') are added automatically
spec.components.schema("Pet", schema=Pet)
spec.components.schema("Cat", schema=Cat)
```

Is it a bug or am I using something incorrectly? Many thanks in advance.

The exact error is:

```py
Traceback (most recent call last):
  File "dataclasses-apispec.py", line 38, in <module>
    spec.components.schema("Cat", schema=Cat)
  File "/home/zdenal/.local/lib/python3.6/site-packages/apispec/core.py", line 177, in schema
    ret.update(plugin.schema_helper(name, component, **kwargs) or {})
  File "/home/zdenal/.local/lib/python3.6/site-packages/dataclasses_jsonschema/apispec.py", line 44, in schema_helper
    self.spec.components.schema(schema_name, schema=json_schemas[schema_name])
  File "/home/zdenal/.local/lib/python3.6/site-packages/apispec/core.py", line 170, in schema
    'Another schema with name "{}" is already registered.'.format(name)
apispec.exceptions.DuplicateComponentNameError: Another schema with name "Category" is already registered.
```

However, this example without usage of dataclasses seems to work fine (no exception):

```py
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin
from flask import Flask, jsonify
from marshmallow import Schema, fields


# Create an APISpec
spec = APISpec(
    title="Swagger Petstore",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[FlaskPlugin(), MarshmallowPlugin()],
)

# Optional marshmallow support
class CategorySchema(Schema):
    id = fields.Int()
    name = fields.Str(required=True)


class PetSchema(Schema):
    category = fields.Nested(CategorySchema, many=True)
    name = fields.Str()
    
class CatSchema(PetSchema):
    color = fields.Str()


# Register entities and paths
spec.components.schema("Pet", schema=PetSchema)
spec.components.schema("Cat", schema=CatSchema)
```

**Comment by s-knibbs** [comment]
Yeah, I think this is happening because when `Pet` and `Cat` are both trying to add `Category` as a schema. However, you only need to add `Cat` to the api-spec since `Pet` is added as a dependency of `Cat`:

```python
from typing import Optional, List
from dataclasses import dataclass

from apispec import APISpec

from dataclasses_jsonschema.apispec import DataclassesPlugin
from dataclasses_jsonschema import JsonSchemaMixin


# Create an APISpec
spec = APISpec(
    title="Swagger Petstore",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[DataclassesPlugin()],
)


@dataclass
class Category(JsonSchemaMixin):
    """Pet category"""
    name: str
    id: Optional[int]

@dataclass
class Pet(JsonSchemaMixin):
    """A pet"""
    categories: List[Category]
    name: str
    
@dataclass
class Cat(Pet):
    """A cat"""
    color: str

spec.components.schema("Cat", schema=Cat)

>>> print(json.dumps(spec.to_dict(), indent=2))
{
  "paths": {},
  "info": {
    "title": "Swagger Petstore",
    "version": "1.0.0"
  },
  "openapi": "3.0.2",
  "components": {
    "schemas": {
      "Category": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          }
        },
        "description": "Pet category"
      },
      "Pet": {
        "type": "object",
        "required": [
          "categories",
          "name"
        ],
        "properties": {
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Category"
            }
          },
          "name": {
            "type": "string"
          }
        },
        "description": "A pet"
      },
      "Cat": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "required": [
              "color"
            ],
            "properties": {
              "color": {
                "type": "string"
              }
            }
          }
        ],
        "description": "A cat"
      }
    }
  }
}
```

**Comment by s-knibbs** [comment]
Although the workaround above works, this issue will currently prevent multiple dataclasses inheriting from the same class to be added.

**Comment by ZdenekM** [comment]
Thanks for your feedback. You are right - in the first example, it is ok to add just ```Cat```. Then consider the following case - when one wants to reuse definitions.

This does not work (raises DuplicateComponentNameError):

```py
from typing import Optional, List
from dataclasses import dataclass

from apispec import APISpec

from dataclasses_jsonschema.apispec import DataclassesPlugin
from dataclasses_jsonschema import JsonSchemaMixin


# Create an APISpec
spec = APISpec(
    title="Swagger Petstore",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[DataclassesPlugin()],
)


@dataclass
class Category(JsonSchemaMixin):
    """Pet category"""
    name: str
    id: Optional[int]

@dataclass
class Pet(JsonSchemaMixin):
    """A pet"""
    categories: List[Category]
    name: str
    
@dataclass
class SomeOtherClass(JsonSchemaMixin):
    categories: List[Category]
    whatever: str

# Dependant schemas (e.g. 'Category') are added automatically
spec.components.schema("SomeOtherClass", schema=SomeOtherClass)
spec.components.schema("Pet", schema=Pet)
```

...while its equivalent using just apispec works:

```py
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin
from flask import Flask, jsonify
from marshmallow import Schema, fields


# Create an APISpec
spec = APISpec(
    title="Swagger Petstore",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[FlaskPlugin(), MarshmallowPlugin()],
)

# Optional marshmallow support
class CategorySchema(Schema):
    id = fields.Int()
    name = fields.Str(required=True)


class PetSchema(Schema):
    category = fields.Nested(CategorySchema, many=True)
    name = fields.Str()
    
class AlternateSchema(Schema):
    category = fields.Nested(CategorySchema, many=True)
    whatever = fields.Str()


# Register entities and paths
spec.components.schema("Pet", schema=PetSchema)
spec.components.schema("AlternateSchema", schema=AlternateSchema)
```

**Comment by ZdenekM** [comment]
It works now as expected, great!
