### ISSUE TITLE
Enum field fails on to_dict

### ISSUE THREAD

**Issue by Garito** [s-knibbs/dataclasses-jsonschema#98]
Hi!
Could you explain me what I'm doing wrong here?
The openapi schema is correct though

```python
>>> from enum import Enum
>>> from dataclasses import dataclass
>>> from dataclasses_jsonschema import JsonSchemaMixin
>>> class Enum1(Enum):
...     VAL1 = "value1"
...     VAL2 = "value2"
...     VAL3 = "value3"
...
>>> @dataclass
... class Test(JsonSchemaMixin):
...     enum1: Enum1
...
>>> test1 = Test(enum1 = "value1")
>>> test1
Test(enum1='value1')
>>> test1.to_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dataclasses_jsonschema/__init__.py", line 338, in to_dict
    value = self._encode_field(field.type, getattr(self, field.name), omit_none)
  File "/usr/local/lib/python3.7/site-packages/dataclasses_jsonschema/__init__.py", line 300, in _encode_field
    return encoder(field_type, value, omit_none)
  File "/usr/local/lib/python3.7/site-packages/dataclasses_jsonschema/__init__.py", line 265, in encoder
    def encoder(_, v, __): return v.value
AttributeError: 'str' object has no attribute 'value'
>>> Test.json_schema()
{'type': 'object', 'required': ['enum1'], 'properties': {'enum1': {'type': 'string', 'enum': ['value1', 'value2', 'value3']}}, 'description': 'Test(enum1: __main__.Enum1)', '$schema': 'http://json-schema.org/draft-06/schema#'}
```

Thanks

**Comment by Garito** [comment]
My bad
I've seen the problem by myself
Sorry
